
export const URLS=[
    {
     front:"./images/joker-red.webp",
     back:"./images/card-back.png",
     value:14
    },
    {
      front:"./images/king-clover.webp",
      back:"./images/card-back.png",
      value:13
    }, 
    {
     front:"./images/king-heart.webp",
     back:"./images/card-back.png",
     value:13
    }, 
    {
     front:"./images/joker-black.webp",
     back:"./images/card-back.png",
     value:14
    },
///////////////////////////////////////////
    {
      front:"./images/ace-dia.webp",
      back:"./images/card-back.png",
      value:1
     },
     {
       front:"./images/ace-spade.webp",
       back:"./images/card-back.png",
       value:1
     }, 
     {
      front:"./images/eight-dia.webp",
      back:"./images/card-back.png",
      value:8
     }, 
     {
      front:"./images/eight-spade.webp",
      back:"./images/card-back.png",
      value:8
     },
////////////////////////////////////////////////////
     {
      front:"./images/five-clover.webp",
      back:"./images/card-back.png",
      value:5
     },
     {
       front:"./images/five-dia.webp",
       back:"./images/card-back.png",
       value:5
     }, 
     {
      front:"./images/four-heart.webp",
      back:"./images/card-back.png",
      value:4
     }, 
     {
      front:"./images/four-spade.webp",
      back:"./images/card-back.png",
      value:4
     },
///////////////////////////////////////////
     {
      front:"./images/nine-heart.webp",
      back:"./images/card-back.png",
      value:9
     },
     {
       front:"./images/nine-spade.webp",
       back:"./images/card-back.png",
       value:9
     }, 
     {
      front:"./images/seven-heart.webp",
      back:"./images/card-back.png",
      value:7
     }, 
     {
      front:"./images/seven-spade.webp",
      back:"./images/card-back.png",
      value:7
     },
     ///////////////////////////
     {
      front:"./images/six-clover.webp",
      back:"./images/card-back.png",
      value:6
     },
     {
       front:"./images/six-dia.webp",
       back:"./images/card-back.png",
       value:6
     }, 
     {
      front:"./images/ten-clover.webp",
      back:"./images/card-back.png",
      value:10
     }, 
     {
      front:"./images/ten-dia.webp",
      back:"./images/card-back.png",
      value:10
     },
     ///////////////
     {
      front:"./images/two-heart.webp",
      back:"./images/card-back.png",
      value:2
     },
     {
       front:"./images/two-dia.webp",
       back:"./images/card-back.png",
       value:2
     }, 
     {
      front:"./images/three-dia.webp",
      back:"./images/card-back.png",
      value:3
     }, 
     {
      front:"./images/three-spade.webp",
      back:"./images/card-back.png",
      value:3
     },
     ////////////////
     {
      front:"./images/queen-heart.webp",
      back:"./images/card-back.png",
      value:12
     },
     {
       front:"./images/queen-spade.webp",
       back:"./images/card-back.png",
       value:12
     }, 
     {
      front:"./images/jack-heart.webp",
      back:"./images/card-back.png",
      value:11
     }, 
     {
      front:"./images/jack-spade.webp",
      back:"./images/card-back.png",
      value:11
     },
     
]

